8 describe dataset
farinaleo/ft_dslr pull request #16
Opened 2024-06-11 13:06 UTC by farinaleo

add the describe required function.
See issue for usage.

2024-06-11 13:30 UTC, kazourak commented on srcs/descibe/tools.py
> +
this function only call read_csv pandas function, why ?

2024-06-11 13:30 UTC, kazourak requested changes
the directory name is "descibe" instead of "describe".

2024-06-12 10:28 UTC, farinaleo commented on srcs/descibe/tools.py
> +
more simple if we decide to normalise data.

2024-06-12 10:29 UTC, farinaleo commented
> the directory name is "descibe" instead of "describe".
Thanks, problem fixed

2024-06-12 10:35 UTC, kazourak approved these changes
thanks, great.

2024-06-12 10:36 UTC, merged